export interface Book {
  id: string;
  title: string;
  author: string;
  coverImage: string;
  favoriteQuotes: string[];
  year?: number;
  genre?: string;
}

export const books: Book[] = [
  {
    id: crypto.randomUUID(),
    title: "Atomic Habits",
    author: "James Clear",
    coverImage: "/atomic-habits.jpg",
    favoriteQuotes: [],
    year: 2018,
    genre: "Self-Help",
  },
  {
    id: crypto.randomUUID(),
    title: "Deep Work",
    author: "Cal Newport",
    coverImage: "/deep-work.jpg",
    favoriteQuotes: [],
    year: 2016,
    genre: "Productivity",
  },
  {
    id: crypto.randomUUID(),
    title: "The Design of Everyday Things",
    author: "Don Norman",
    coverImage: "/design-everyday-things.jpg",
    favoriteQuotes: [],
    year: 1988,
    genre: "Design",
  },
  {
    id: crypto.randomUUID(),
    title: "Clean Code",
    author: "Robert C. Martin",
    coverImage: "/clean-code.jpg",
    favoriteQuotes: [],
    year: 2008,
    genre: "Programming",
  },
  {
    id: crypto.randomUUID(),
    title: "Steve Jobs",
    author: "Walter Isaacson",
    coverImage: "/steve-jobs.jpg",
    favoriteQuotes: [],
    year: 2011,
    genre: "Biography",
  },
  {
    id: crypto.randomUUID(),
    title: "Forever Strong",
    author: "Dr. Gabrielle Lyon",
    coverImage: "/forever-strong.jpg",
    favoriteQuotes: [],
    year: 2024,
    genre: "Self-Help",
  },
  {
    id: crypto.randomUUID(),
    title: "Can't Hurt Me",
    author: "David Goggins",
    coverImage: "/cant-hurt-me.jpg",
    favoriteQuotes: ["Stay strong", "Cookie Jar"],
    year: 2018,
    genre: "Self-Help, Autobiography",
  },
  {
    id: crypto.randomUUID(),
    title: "Never Finished",
    author: "David Goggins",
    coverImage: "/never-finished.jpg",
    favoriteQuotes: [],
    year: 2022,
    genre: "Self-Help, Autobiography",
  },
  {
    id: crypto.randomUUID(),
    title: "The Art of War",
    author: "Sun Tzu",
    coverImage: "/art-of-war.jpg",
    favoriteQuotes: [],
    year: 500,
    genre: "Philosophy",
  },
  {
    id: crypto.randomUUID(),
    title: "L'éveil des consciences ou comment devenir un homme libre",
    author: "Frédéric Delavier",
    coverImage: "/leveil-des-consciences.jpg",
    favoriteQuotes: ["Je suis, celui qui est."],
    year: 2018,
    genre: "Philosophy",
  },
  {
    id: crypto.randomUUID(),
    title: "Clean Architecture",
    author: "Robert C. Martin",
    coverImage: "/clean-architecture.jpg",
    favoriteQuotes: [],
    year: 2017,
    genre: "Programming",
  },
  {
    id: crypto.randomUUID(),
    title: "Refactoring",
    author: "Martin Fowler, Kent Beck",
    coverImage: "/refactoring.jpg",
    favoriteQuotes: [],
    year: 1999,
    genre: "Programming",
  },
  {
    id: crypto.randomUUID(),
    title: "Start with a why",
    author: "Simon Sinek",
    coverImage: "/start-with-why.jpg",
    favoriteQuotes: [],
    year: 2011,
    genre: "Self-Help",
  },
  {
    id: crypto.randomUUID(),
    title: "Why we sleep",
    author: "Matthew Walker",
    coverImage: "/why-we-sleep.jpg",
    favoriteQuotes: [],
    year: 2017,
    genre: "Health",
  },
  {
    id: crypto.randomUUID(),
    title: "Chatter: The Voice in Our Head",
    author: "Ethan Kross",
    coverImage: "/chatter.jpg",
    favoriteQuotes: [],
    year: 2021,
    genre: "Psychology",
  },
  {
    id: crypto.randomUUID(),
    title: "The Subtle Art of Not Giving a F*ck",
    author: "Mark Manson",
    coverImage: "/subtle-art.jpg",
    favoriteQuotes: [],
    year: 2016,
    genre: "Self-Help",
  },
  {
    id: crypto.randomUUID(),
    title: "Everything Is F*cked",
    author: "Mark Manson",
    coverImage: "/everything-is-fcked.jpg",
    favoriteQuotes: [],
    year: 2018,
    genre: "Self-Help",
  },
  {
    id: crypto.randomUUID(),
    title: "Elon Musk: Tesla, SpaceX, and the Quest for a Fantastic Future",
    author: "Ashlee Vance",
    coverImage: "/elon-musk.jpg",
    favoriteQuotes: [],
    year: 2015,
    genre: "Biography",
  },
  {
    id: crypto.randomUUID(),
    title: "Universal Principles of UX",
    author: "Irene Pereyra",
    coverImage: "/universal-principles-ux.jpg",
    favoriteQuotes: [],
    year: 2023,
    genre: "Design",
  },
  {
    id: crypto.randomUUID(),
    title: "The Alchemist",
    author: "Paulo Coelho",
    coverImage: "/the-alchemist.jpg",
    favoriteQuotes: [],
    year: 1988,
    genre: "Philosophy",
  },
  {
    id: crypto.randomUUID(),
    title: "Engineering Management for the Rest of Us",
    author: "Sarah Drasner",
    coverImage: "/engineering-management.jpg",
    favoriteQuotes: [],
    year: 2022,
    genre: "Management",
  },
  {
    id: crypto.randomUUID(),
    title: "The Courage to Be Disliked",
    author: "Ichiro Kishimi, Fumitake Koga",
    coverImage: "/courage-to-be-disliked.jpg",
    favoriteQuotes: [],
    year: 2013,
    genre: "Philosophy",
  },
  {
    id: crypto.randomUUID(),
    title: "Structures : Or Why Things Don't Fall Down",
    author: "J. E. Gordon",
    coverImage: "/structures.jpg",
    favoriteQuotes: [],
    year: 2003,
    genre: "Architecture",
  },
  {
    id: crypto.randomUUID(),
    title: "Computer Networks (4th Edition)",
    author: "Andrew S. Tanenbaum, David J. Wetherall",
    coverImage: "/computer-networks.jpg",
    favoriteQuotes: [],
    year: 2010,
    genre: "Computer Science",
  },
  {
    id: crypto.randomUUID(),
    title: "Comment leur dire...: La Process Communication",
    author: "Gérard Collignon",
    coverImage: "/process-communication.jpg",
    favoriteQuotes: [],
    year: 2005,
    genre: "Management ",
  },
  {
    id: crypto.randomUUID(),
    title: "The DevOps Handbook",
    author:
      "Gene Kim, Patrick Debois, John Willis, Jez Humble, and Andrew Shafer",
    coverImage: "/devops-handbook.jpg",
    favoriteQuotes: [],
    year: 2016,
    genre: "Computer Science",
  },
  {
    id: crypto.randomUUID(),
    title: "AI Engineering",
    author: "Chip Huyen",
    coverImage: "/ai-engineering.jpg",
    favoriteQuotes: [],
    year: 2024,
    genre: "Computer Science",
  },
];
